In [1]:
import numpy as np
import pandas as pd
import xlrd
import matplotlib.pyplot as plt
import random
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

In [2]:
df = pd.read_excel("Water Data's Ariani for PCA.xlsx")

In [3]:
df2 = df.copy()

In [4]:
p = np.linspace(0.01,2*0.01, 5)
z = random.choice(p[1:-1])
z

0.0125

In [5]:
for l,c in df2.items():    
    for i in c.index:
        s = str(c[i])
        if s.isalpha():
            c.iat[i] = np.nan            
        elif '<' in s:
            x = s.replace('<','')
            y = float(x)
            p = np.linspace(0, y, 5)
            z = random.choice(p[1:-1])
            # print(f"{l}->{i}: {c[i]} {x} -> {y} -> {z}")
            c.iat[i] = z
        elif '>' in s:
            x = s.replace('>','')
            y = float(x)
            p = np.linspace(y, 2*y, 5)
            z = random.choice(p[1:-1])
            # print(f"{l}->{i}: {c[i]} {x} -> {y} -> {z}")
            c.iat[i] = z

In [6]:
df2

SMP-DAT DO (% Sat)   DO (mg/l) BOD (mg/l) COD (mg/l)  \
0    2000-01-23 00:00:00        40.7       3.39          1         19   
1    2000-02-27 00:00:00        58.1       4.79          6         20   
2    2000-03-27 00:00:00        65.1       5.34          1         19   
3    2000-04-26 00:00:00        68.1       5.58          7         19   
4    2000-05-30 00:00:00        55.1       4.46          2         19   
..                   ...         ...        ...        ...        ...   
214  2018-05-02 15:12:00      88.296      6.902          4         14   
215  2018-07-03 11:06:00      94.002      7.719          4         15   
216  2018-09-03 09:37:00      82.502      6.771          4         14   
217  2018-11-02 08:54:00          89      7.329          7         21   
218              SMP-DAT   DO\n% Sat  DO \nmg/l  BOD\nmg/l  COD\nmg/l   

    SS (mg/l) pH (unit) NH3-NL (mg/l) TEMP (Deg C)    COND (uS)  ...  \
0          26      5.79          0.08        24.78         53.7  ...   
1          14      5.63        0.0025        25.25         50.7  ...   
2          23      5.76        0.0075        25.51         53.7  ...   
3          35      5.66         0.005        25.66         51.9  ...   
4          43      6.09           0.3        26.08         61.5  ...   
..        ...       ...           ...          ...          ...  ...   
214       118     6.055          0.11        28.07       76.727  ...   
215        36     6.594          0.07       25.334       67.954  ...   
216        29     6.547          0.14       25.364       81.267  ...   
217        19     6.548           0.1        25.18       81.481  ...   
218  SS\nmg/l       NaN   NH3-N\nmg/l    TEMP\n °C  COND\nmS/cm  ...   

     TUR (NTU)  DS (mg/l)  TS (mg/l)  NO3 (mg/l) PO4 (mg/l) OG (mg/l)  \
0         74.0       75.1      101.1        0.89       0.01      0.75   
1         54.0       40.0       54.0        0.88       0.03         2   
2         78.0       39.0       86.0        0.62      0.005       0.5   
3        140.0       28.0       63.0        0.68      0.005       0.5   
4         89.0       23.0       66.0        0.09      0.005      0.75   
..         ...        ...        ...         ...        ...       ...   
214        NaN        NaN        NaN        5.26     0.0025       NaN   
215        NaN        NaN        NaN        3.65        NaN       NaN   
216        NaN        NaN        NaN        2.59     0.0025       NaN   
217        NaN        NaN        NaN        4.82     0.0075       NaN   
218        NaN        NaN        NaN   NO3\nmg/l  PO4\nmg/l       NaN   

    MBAS (mg/l) E-coli (cfu/100ml)       Coliform (cfu/100ml)    WQI  
0         0.025                190                       2000  64.40  
1         0.025               3000                       6000  59.62  
2        0.0375               1500                       3900  65.00  
3        0.0125               6000                       9000  40.89  
4         0.025               4300                       5500  47.22  
..          ...                ...                        ...    ...  
214         NaN                600                      39000  48.03  
215         NaN               1000                      34000  47.50  
216         NaN               2600                      51000  29.32  
217         NaN               1200                      50000  65.74  
218         NaN  E-coli\ncfu/100ml  Total Coliform\ncfu/100ml    NaN  

[219 rows x 21 columns]

In [7]:
df3 = df2.dropna()

In [8]:
df3.shape

(207, 21)

In [9]:
df3.columns

Index(['SMP-DAT', 'DO (% Sat) ', 'DO (mg/l)', 'BOD (mg/l)', 'COD (mg/l)',
       'SS (mg/l)', 'pH (unit)', 'NH3-NL (mg/l)', 'TEMP (Deg C)', 'COND (uS)',
       'SAL (ppt)', 'TUR (NTU)', 'DS (mg/l)', 'TS (mg/l)', 'NO3 (mg/l)',
       'PO4 (mg/l)', 'OG (mg/l)', 'MBAS (mg/l)', 'E-coli (cfu/100ml)',
       'Coliform (cfu/100ml)', 'WQI'],
      dtype='object')

In [10]:
columns = list(df3.columns)
features = columns[1:-1]

In [11]:
target = columns[-1]

In [12]:
x_data = df3.loc[:, features]
y_target = df3.loc[:,target]

In [13]:
x_data.shape, y_target.shape

((207, 19), (207,))

In [14]:
y_target = y_target.round(decimals=-1)

In [15]:
x_data.shape, y_target.shape

((207, 19), (207,))

In [16]:
x_data2 = StandardScaler().fit_transform(x_data)

In [17]:
# split data into train and test
train_data, test_data, train_lbl, test_lbl = train_test_split( x_data2, y_target, test_size=1/7.0, random_state=0)

In [18]:
train_data

array([[-0.70588423, -0.70660963, -0.87701416, ...,  0.14187781,
        -0.157469  , -0.51314576],
       [ 0.4170598 ,  0.42010615,  0.03297046, ..., -0.10077027,
        -0.37132132,  0.4157835 ],
       [-0.32924461, -0.32250198,  2.307932  , ...,  0.14187781,
        -0.12182695,  1.14080146],
       ...,
       [-0.38504307, -0.2627519 ,  0.03297046, ..., -0.10077027,
         0.76922438,  0.03816998],
       [ 0.52168191,  0.57374921, -0.42202185, ...,  0.14187781,
        -0.33567927, -0.24126403],
       [ 0.52865672,  0.45424905,  0.94295508, ...,  6.65763886,
        -0.37132132,  0.18921539]])

In [19]:
train_data.shape, test_data.shape

((177, 19), (30, 19))

In [20]:
pca = PCA(0.95)

In [21]:
pca.fit(train_data)

PCA(n_components=0.95)

In [22]:
pca.n_components_

12

In [23]:
ttrain_data = pca.transform(train_data)
ttest_data = pca.transform(test_data)

In [24]:
ttrain_data.shape, ttest_data.shape

((177, 12), (30, 12))

In [25]:
pca.explained_variance_ratio_

array([0.26998494, 0.13644993, 0.11228057, 0.0808654 , 0.0696293 ,
       0.06169054, 0.05808226, 0.05105435, 0.04323999, 0.03873602,
       0.02652545, 0.01947727])

In [26]:
# all parameters not specified are set to their defaults
# default solver is incredibly slow which is why it was changed to 'lbfgs'
logisticRegr = LogisticRegression(solver = 'lbfgs')

In [27]:
logisticRegr.fit(ttrain_data, train_lbl)

LogisticRegression()

In [28]:
logisticRegr.predict(ttest_data[0].reshape(1,-1))

array([70.])

In [29]:
logisticRegr.predict(ttest_data[:])

array([70., 50., 50., 30., 60., 60., 50., 40., 50., 60., 50., 60., 50.,
       60., 50., 50., 50., 60., 50., 50., 60., 60., 60., 50., 50., 50.,
       50., 40., 50., 40.])

In [30]:
logisticRegr.score(ttest_data, test_lbl)

0.4